### ISSUE TITLE
PyPi distribution 

### ISSUE THREAD

**Issue by markrichardson** [chebpy/chebpy#53]
Issue to collect thoughts on setting up "pip install chebfun" user installation

**Comment by janniklasrose** [comment]
Good idea! Now that the project is using modern `setuptools` it should be fairly straightforward to deploy to PyPi.

What I'm thinking is to use a GitHub Action that runs with every release tag [(example from GitHub docs)](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags):
```yaml
on:
  push:
    branches:
      - master
    tags:
      - v*
```
